apiVersion: apps/v1
kind: Deployment
metadata:
  name: analysis-agent
  namespace: pipeline
  labels:
    app: analysis-agent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analysis-agent
  template:
    metadata:
      labels:
        app: analysis-agent
    spec:
      containers:
      - name: analysis-agent
        image: registry.example.com/pipeline/analysis-agent:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8000
        env:
        - name: MESSAGE_BUS_URL
          valueFrom:
            secretKeyRef:
              name: mcp-use-secret
              key: url
        - name: MESSAGE_BUS_USERNAME
          valueFrom:
            secretKeyRef:
              name: mcp-use-secret
              key: username
        - name: MESSAGE_BUS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mcp-use-secret
              key: password
        - name: SWARMS_ENABLED
          value: "true"
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-secret
              key: apiKey
        - name: VECTORSTORE_URL
          valueFrom:
            secretKeyRef:
              name: vectorstore-secret
              key: url
        - name: LOG_LEVEL
          value: "INFO"
        volumeMounts:
        - name: config
          mountPath: /app/config
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            cpu: "100m"
            memory: "200Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"
      volumes:
      - name: config
        configMap:
          name: analysis-agent-config
---
apiVersion: v1
kind: Service
metadata:
  name: analysis-agent
  namespace: pipeline
  labels:
    app: analysis-agent
spec:
  selector:
    app: analysis-agent
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: analysis-agent-hpa
  namespace: pipeline
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: analysis-agent
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75