apiVersion: v1
kind: ConfigMap
metadata:
  name: planning-agent-config
  namespace: pipeline
data:
  MCP_BROKER_URL: "mcp-use://broker:9092"
  SWARMS_DISCOVERY_URL: "swarm://service-discovery:5701"
  ANALYSIS_TOPIC: "tasks.analysis"
  PLANNING_TOPIC: "tasks.planning"
  LOG_LEVEL: "INFO"
---
apiVersion: v1
kind: Secret
metadata:
  name: planning-agent-secrets
  namespace: pipeline
type: Opaque
stringData:
  OPENAI_API_KEY: ""
  VECTORSTORE_API_KEY: ""
  VECTORSTORE_URL: "https://vectorstore.endpoint"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: planning-agent
  namespace: pipeline
  labels:
    app: planning-agent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: planning-agent
  template:
    metadata:
      labels:
        app: planning-agent
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: planning-agent
          image: myregistry/planning-agent:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: planning-agent-config
            - secretRef:
                name: planning-agent-secrets
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: AGENT_ENV
              value: "production"
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 3
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: planning-agent-service
  namespace: pipeline
  labels:
    app: planning-agent
spec:
  selector:
    app: planning-agent
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: planning-agent-hpa
  namespace: pipeline
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: planning-agent
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75